package net.maui.morselab.decoder

import net.maui.morselab.generator.MorseSoundGenerator
import net.maui.morselab.utils.AudioUtils
import org.junit.Assert
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Test
import kotlin.math.min

class MorseDecoderTest {

    // --- Test Configuration ---
    // sampleRate and targetFreq will be set dynamically or are handled by the decoder
    private val blockSize = 512
    private val targetFreq = 700.0 // For generator
    private val wpm = 20
    private val farnsworthWpm = 20

    private lateinit var decoder: MorseDecoder

    private val morseSoundGenerator = MorseSoundGenerator()
    private var decodedString = ""

    // Use a single helper to run the test logic
    private fun runTestFor(text: String) {
        // Reset decoder and string for each run
        decodedString = ""
        decoder = MorseDecoder(
            onDecoded = { decoded ->
                decodedString += decoded
            },
            // Use a fixed sample rate for generated audio
            sampleRate = 16000,
            blockSize = blockSize
        )
        decoder.reset()


        val audioByteArray = morseSoundGenerator.generate(
            text = "$text ", // Add trailing space for word gap
            wpm = wpm,
            farnsworthWpm = farnsworthWpm,
            frequency = targetFreq.toInt(),
            sampleRate = 16000
        )

        val audioFloatArray = AudioUtils.bytesToFloat(byteArray = audioByteArray)
        feedDataToDecoder(decoder, audioFloatArray, 16000)

        // The assertion is now robust against leading/trailing spaces from the decoder
        assertEquals(text, decodedString.trim())
    }

    @Test
    fun `decoder correctly decodes SOS from audio generated by MorseSoundGenerator`() {
        runTestFor("SOS")
    }

    @Test
    fun `decoder correctly decodes HI from audio generated by MorseSoundGenerator`() {
        runTestFor("HI")
    }

    @Test
    fun `decoder correctly decodes HI SOS from wav file`() {
        val wavFile = WavReader.readWavFile("hi-sos.wav")
        Assert.assertNotNull("Failed to read hi-sos.wav file from resources.", wavFile)
        wavFile!! // Use non-null assertion for convenience

        // Reset decoder and string for this specific test
        decodedString = ""
        decoder = MorseDecoder(
            onDecoded = { decoded ->
                decodedString += decoded
            },
            sampleRate = wavFile.sampleRate,
            blockSize = blockSize
        )
        decoder.reset()

        val audioFloatArray = AudioUtils.bytesToFloat(wavFile.audioData)
        feedDataToDecoder(decoder, audioFloatArray, wavFile.sampleRate)

        // Make the assertion robust against extra spaces
        assertEquals("HI SOS", decodedString.trim())
    }


    /**
     * Helper function to chunk a larger audio array into blocks and pass them to the decoder.
     */
    private fun feedDataToDecoder(decoder: MorseDecoder, audioData: FloatArray, sampleRate: Int) {
        var offset = 0
        while (offset < audioData.size) {
            val remaining = audioData.size - offset

            // --- THE MOST IMPORTANT FIX IS HERE ---
            // This is the number of actual audio samples we're processing in this iteration.
            val numSamplesInBlock = min(blockSize, remaining)
            // --- END OF FIX ---

            val block = audioData.copyOfRange(offset, offset + numSamplesInBlock)

            // The 'finalBlock' is always padded to the full blockSize for the Goertzel algorithm
            val finalBlock = if (block.size < blockSize) {
                block.copyOf(blockSize) // Pads with 0f by default
            } else {
                block
            }

            // --- THE MOST IMPORTANT FIX IS HERE ---
            // Pass the correct number of samples, not 0.
            decoder.processBuffer(finalBlock, numSamplesInBlock)
            // --- END OF FIX ---

            offset += numSamplesInBlock
        }
        // After all audio is processed, flush any remaining characters from the buffer.
        decoder.flush()
    }
}
